---
title: "br_anova"
author: "Fernando Rawicz"
date: "25/07/2021"
output: html_document
---

```{r message = FALSE}
rm(list =ls())
options(scipen = 9999)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
set.seed(415)

library(tidyverse)
library(rstan)
# library(shinystan)
library(stringr)
library(dplyr)
library(readxl)
library(gtools)
library(rjags)
library(runjags)
library(brms)
library(knitr)
library(DT)
library(HDInterval)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

fileNameRoot = "teupaidecalcinha"


candidates <- c("PSL", "PT", "PDT", "PSC", "PSDB", "PSOL", "PMDB", "NOVO", "PPL", "REDE", "PSTU")

br_datafolha <- read_excel("data/pollsbrazil.xltx", sheet = "Datafolha")%>% 
  filter(Party %in% candidates)%>% 
  # mutate(Partyiid = match(Party , sort(unique(Party)))) %>% 
  mutate(Bias = Result  - Poll ) %>% 
  mutate(Company = "Datafolha")


br_ibope <- read_excel("data/pollsbrazil.xltx", sheet = "Ibope")%>% 
  filter(Party %in% candidates)%>% 
  # mutate(Partyiid = match(Party , sort(unique(Party)))) %>% 
  mutate(Bias = Poll - Result) %>% 
  mutate(Company = "Ibope")



br_bias_final <- rbind(br_datafolha, br_ibope) %>% 
  mutate(Companyiid = match(Company , sort(unique(Company))))  %>% 
  mutate(Eleciid = match(Election , sort(unique(Election)))) %>% 
  mutate(Partyiid = match(Party , sort(unique(Party))))


```




## BAYESIAN ANOVA

```{r}


source("anovafunc.R")

  y = as.numeric(br_bias_final$Bias)
  x1 = as.numeric(as.factor(br_bias_final$Party))
  x1levels = levels(as.factor(br_bias_final$Party))
  x2 = as.numeric(as.factor(br_bias_final$Company))
  x2levels = levels(as.factor(br_bias_final$Company))
  Ntotal = length(y)
  Nx1Lvl = length(unique(x1))
  Nx2Lvl = length(unique(x2))
  yMean = mean(y)
  ySD = sd(y)
  agammaShRa = unlist( gammaShRaFromModeSD( mode=sd(y)/2 , sd=2*sd(y) ) )

  
  dataList = list(
    y = y ,
    x1 = x1 ,
    x2 = x2 ,
    Ntotal = Ntotal ,
    Nx1Lvl = Nx1Lvl ,
    Nx2Lvl = Nx2Lvl ,
    # data properties for scaling the prior:
    yMean = yMean ,
    ySD = ySD ,
    agammaShRa = agammaShRa 
  )



mcmcCoda = genMCMC(y, x1,x2, x1levels, x2levels,mu0 = 1.5, mu1 = 6 ,
                    numSavedSteps=15000 , thinSteps=5,
                   nChains = 3 )



parameterNames = varnames(mcmcCoda) 
show( parameterNames ) # show all parameter names, for reference
for ( parName in c("b0","b1[1]","b2[1]","b1b2[1,1]","ySigma") ) {
  diagMCMC( codaObject=mcmcCoda , parName=parName , 
            saveName=fileNameRoot , saveType=graphFileType )
}



summbr <- summary(mcmcCoda)

sumbrstat <- summbr$statistics %>% as.data.frame()

interval95 <- t(hdi(mcmcCoda, credMass = 0.95)) %>% as.data.frame() %>%  rename("HDI Lower 95" = lower,"HDI Upper 95" = upper )
interval90 <- t(hdi(mcmcCoda, credMass = 0.9)) %>% as.data.frame() %>%  rename("HDI Lower 90" = lower,"HDI Upper 90" = upper )

finstatbr <- cbind(sumbrstat, interval95, interval90) %>% 
  mutate_if(is.numeric, round,2) %>% 
  select(-c("Naive SE", "Time-series SE"))

library(xtable)

xtable(finstatbr)

```





## Sentisivity analysis





```{r}


mcmcCoda1 = genMCMC(y, x1,x2, x1levels, x2levels,mu0 = 2.5, mu1 = 12.5,
                    numSavedSteps=15000 , thinSteps=5,
                   nChains = 3 )

mcmcCoda2 = genMCMC(y, x1,x2, x1levels, x2levels,mu0 = 5, mu1 = 50,
                    numSavedSteps=15000 , thinSteps=5,
                   nChains = 3 )



summbr1 <- summary(mcmcCoda1)
summbr2 <- summary(mcmcCoda2)


sumbrstat1 <- summbr1$statistics %>% as.data.frame() %>% select("Mean model 1" = "Mean", "SD model 1" = "SD")
sumbrstat2 <- summbr2$statistics %>% as.data.frame() %>% select("Mean model 2" = "Mean", "SD model 2" = "SD")


interval95model1 <- t(hdi(mcmcCoda1, credMass = 0.95)) %>% as.data.frame() %>%  rename("HDI Lower 95 model 1" = lower,"HDI Upper 95 model 1" = upper )
interval95model2 <- t(hdi(mcmcCoda2, credMass = 0.95)) %>% as.data.frame() %>%  rename("HDI Lower 95 model 2" = lower,"HDI Upper 95 model 2" = upper )


finstatbrensi <- cbind(sumbrstat1, sumbrstat2) %>% 
  mutate_if(is.numeric, round,2)


xtable(finstatbrensi)

```












