---
title: "pt_marginal"
author: "Fernando Rawicz"
date: "30/05/2021"
output: html_document
---


```{r message = FALSE}
rm(list = ls())
set.seed(1234)
options(scipen = 9999)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

library(rstan)
library(shinystan)
library(stringr)
library(dplyr)
library(readxl)
library(gtools)
library(rjags)
library(runjags)
library(brms)
library(knitr)
library(DT)
library(tidyverse)
library(bsts)
library(MARSS)
library(reshape2)
library(tidybayes)
library(lubridate)
library(gridExtra)
```


## The data 

```{r message = FALSE}
pt_polls <- read_excel("data/pollsportugal.xltx") %>% 
  arrange(Date) %>% 
  mutate(sumlessnull = as.numeric( as.numeric(`PS`) + as.numeric(`CHEGA`) + as.numeric(`PCP`) + as.numeric(`PSD`) +
                           as.numeric(`BE`) + as.numeric(`IL`) + as.numeric(`RIR`) ) )
```

```{r message = FALSE}

  
  pt_polls2 <- pt_polls %>% 
     as.data.frame() %>% 
    mutate(
      PSD = round((as.numeric(PSD) *100) / sumlessnull, 2),
      PS =  round((as.numeric(PS) *100) / sumlessnull, 2),
      CHEGA =  round((as.numeric(CHEGA) *100) / sumlessnull, 2),
      Others =  round((( as.numeric(PCP) + as.numeric(BE) + as.numeric(IL) + as.numeric(RIR) )*100)/sumlessnull, 2)
    ) %>% 
    dplyr::select(c( "Date", "PSD","PS","CHEGA", "Others"))


par(mfrow=c(2,2))

plot.xts(xts(x = pt_polls2$PSD, order.by = as.Date(pt_polls2$Date)), main = "PSD" )
 
plot.xts(xts(x = pt_polls2$PS, order.by = as.Date(pt_polls2$Date)), main = "PS" )

plot.xts(xts(x = pt_polls2$CHEGA, order.by = as.Date(pt_polls2$Date)), main = "CHEGA" )

plot.xts(xts(x = pt_polls2$Others, order.by = as.Date(pt_polls2$Date)), main = "Others" )
  
```


## Univariate space state model

```{r message = FALSE}

jagsscriptss <- "
model {  
   # priors on parameters
   u ~ dnorm(0, 1); 
   inv.q ~ dgamma(1, 3); 
   q <- 1/inv.q;
   inv.r ~ dgamma(mu0, mu1);
   r <- 1/inv.r; 
   X0 ~ dnorm(Y1, 0.1);
   
   X[1] ~ dnorm(X0 + u, inv.q);
   EY[1] <- X[1];
   Y[1] ~ dnorm(EY[1], inv.r);
   for(i in 2:N) {
      X[i] ~ dnorm(X[i-1] + u, inv.q);
      EY[i] <- X[i];
      Y[i] ~ dnorm(EY[i], inv.r); 
   }
}  
"
jags.paramsss <- c("q", "r", "EY", "u")

jags.datass.psd <- list(Y = as.vector(pt_polls2$PSD), N = length(as.vector(pt_polls2$PSD)), Y1 = as.vector(pt_polls2$PSD)[1], mu0 = 1.5, mu1 = 6)
jags.datass.ps <- list(Y = as.vector(pt_polls2$PS), N = length(as.vector(pt_polls2$PS)), Y1 = as.vector(pt_polls2$PS)[1], mu0 = 1.5, mu1 = 6)
jags.datass.chega <- list(Y = as.vector(pt_polls2$CHEGA), N = length(as.vector(pt_polls2$CHEGA)), Y1 = as.vector(pt_polls2$CHEGA)[1], mu0 = 1.5, mu1 = 6)
jags.datass.others <- list(Y = as.vector(pt_polls2$Others), N = length(as.vector(pt_polls2$Others)), Y1 = as.vector(pt_polls2$Others)[1], mu0 = 1.5, mu1 = 6)

```

```{r message = FALSE}

modss.psd = jags.model(textConnection(jagsscriptss), data=jags.datass.psd, n.chains=3)
update(modss.psd, 1e3)
mod_simss.psd = coda.samples(model=modss.psd, variable.names=jags.paramsss, n.iter=5e3)

modss.ps = jags.model(textConnection(jagsscriptss), data=jags.datass.ps, n.chains=3)
update(modss.ps, 1e3)
mod_simss.ps = coda.samples(model=modss.ps, variable.names=jags.paramsss, n.iter=5e3)

modss.chega = jags.model(textConnection(jagsscriptss), data=jags.datass.chega, n.chains=3)
update(modss.chega, 1e3)
mod_simss.chega = coda.samples(model=modss.chega, variable.names=jags.paramsss, n.iter=5e3)

modss.other = jags.model(textConnection(jagsscriptss), data=jags.datass.others, n.chains=3)
update(modss.other, 1e3)
mod_simss.other = coda.samples(model=modss.other, variable.names=jags.paramsss, n.iter=5e3)


mcmcresultspsd = as.mcmc(do.call(rbind, mod_simss.psd))
mcmcresultsps = as.mcmc(do.call(rbind, mod_simss.ps))
mcmcresultschega = as.mcmc(do.call(rbind, mod_simss.chega))
mcmcresultsother = as.mcmc(do.call(rbind, mod_simss.other))


```

```{r}
(colMeans(round(mcmcresultspsd,2)))
(colMeans(round(mcmcresultsps,2)))
(colMeans(round(mcmcresultschega,2)))
(colMeans(round(mcmcresultsother,2)))


```
## Forecasting

```{r message = FALSE}
datevec <- c(pt_polls2$Date, max(pt_polls2$Date) + days(1), max(pt_polls2$Date) + days(2))

jags.datass.f.psd <- list(Y = as.vector(c(pt_polls2$PSD, NA, NA)), N = length(as.vector(pt_polls2$PSD)) + 2, Y1 = as.vector(pt_polls2$PSD)[1], mu0 = 1.5, mu1 = 6)
jags.datass.f.ps <- list(Y = as.vector(c(pt_polls2$PS, NA, NA)), N = length(as.vector(pt_polls2$PS)) + 2, Y1 = as.vector(pt_polls2$PS)[1], mu0 = 1.5, mu1 = 6)
jags.datass.f.chega <- list(Y = as.vector(c(pt_polls2$CHEGA, NA, NA)), N = length(as.vector(pt_polls2$CHEGA)) + 2, Y1 = as.vector(pt_polls2$CHEGA)[1], mu0 = 1.5, mu1 = 6)
jags.datass.f.others <- list(Y = as.vector(c(pt_polls2$Others, NA, NA)), N = length(as.vector(pt_polls2$Others)) + 2, Y1 = as.vector(pt_polls2$Others)[1], mu0 = 1.5, mu1 = 6)


jags.paramsss <- c("EY")

modss.f.psd = jags.model(textConnection(jagsscriptss), data=jags.datass.f.psd, n.chains=3)
update(modss.f.psd, 1e3)
mod_simss.f.psd = coda.samples(model=modss.f.psd, variable.names=jags.paramsss, n.iter=5e3)

modss.f.ps = jags.model(textConnection(jagsscriptss), data=jags.datass.f.ps, n.chains=3)
update(modss.f.ps, 1e3)
mod_simss.f.ps = coda.samples(model=modss.f.ps, variable.names=jags.paramsss, n.iter=5e3)

modss.f.chega = jags.model(textConnection(jagsscriptss), data=jags.datass.f.chega, n.chains=3)
update(modss.f.chega, 1e3)
mod_simss.f.chega = coda.samples(model=modss.f.chega, variable.names=jags.paramsss, n.iter=5e3)

modss.f.others = jags.model(textConnection(jagsscriptss), data=jags.datass.f.others, n.chains=3)
update(modss.f.others, 1e3)
mod_simss.f.others = coda.samples(model=modss.f.others, variable.names=jags.paramsss, n.iter=5e3)



sumpsd <- summary(mod_simss.f.psd)
sumps <- summary(mod_simss.f.ps)
sumchega <- summary(mod_simss.f.chega)
sumother <- summary(mod_simss.f.others)


```

```{r message = FALSE}

quantilespsd <- sumpsd$quantiles  
ggpsd <- sumpsd$statistics %>% data.frame() %>% dplyr::select("Mean") %>% cbind(datevec) %>% cbind(quantilespsd)

quantilesps <- sumps$quantiles  
ggps <- sumps$statistics %>% data.frame() %>% dplyr::select("Mean") %>% cbind(datevec) %>% cbind(quantilesps)

quantileschega <- sumchega$quantiles  
ggchega <- sumchega$statistics %>% data.frame() %>% dplyr::select("Mean") %>% cbind(datevec) %>% cbind(quantileschega)

quantilesothers <- sumother$quantiles  
ggothers <- sumother$statistics %>% data.frame() %>% dplyr::select("Mean") %>% cbind(datevec) %>% cbind(quantilesothers)


p1 <- ggplot(ggpsd, aes(datevec)) +
   geom_ribbon(aes(ymin = `2.5%`, ymax = `97.5%`), fill = "grey70") +
   geom_line(aes(y = Mean)) +
   labs(x = "Date",y = "%", title = "PSD Valid Vote Share in %")+
  theme(plot.title = element_text(hjust = 0.5))+ 
   geom_vline(xintercept = as.numeric(ggpsd$datevec[c(14)]) ) +
  geom_point(aes(x= ggpsd$datevec[c(16)], y=60.66), colour="red", size =3)


p2 <- ggplot(ggps, aes(datevec)) +
   geom_ribbon(aes(ymin = `2.5%`, ymax = `97.5%`), fill = "grey70") +
   geom_line(aes(y = Mean)) +
   labs(x = "Date",y = "%", title = "PS Valid Vote Share in %")+
  theme(plot.title = element_text(hjust = 0.5))+ 
   geom_vline(xintercept = as.numeric(ggps$datevec[c(14)]) )+
  geom_point(aes(x= ggps$datevec[c(16)], y=12.96), colour="red", size =3)


p3 <- ggplot(ggchega, aes(datevec)) +
   geom_ribbon(aes(ymin = `2.5%`, ymax = `97.5%`), fill = "grey70") +
   geom_line(aes(y = Mean)) +
   labs(x = "Date",y = "%", title = "CHEGA Valid Vote Share in %")+
  theme(plot.title = element_text(hjust = 0.5))+ 
   geom_vline(xintercept = as.numeric(ggchega$datevec[c(14)]) )+
  geom_point(aes(x= ggchega$datevec[c(16)], y=11.93), colour="red", size =3)


p4 <- ggplot(ggothers, aes(datevec)) +
   geom_ribbon(aes(ymin = `2.5%`, ymax = `97.5%`), fill = "grey70") +
   geom_line(aes(y = Mean)) +
   labs(x = "Date", title = "Other parties Valid Vote Share in %", y = "%")+
  theme(plot.title = element_text(hjust = 0.5))+ 
   geom_vline(xintercept = as.numeric(ggothers$datevec[c(14)]) )+
  geom_point(aes(x= ggps$datevec[c(16)], y=14.45), colour="red", size =3)


grid.arrange(p1, p2,p3,p4, nrow = 2)

```

## Forecast 10 days

```{r message = FALSE}
# datevec <- c(pt_polls2$Date, max(pt_polls2$Date) + days(1), max(pt_polls2$Date) + days(2))
pt_polls210 <- pt_polls2 %>% 
   filter(Date < "2021-01-10")


jags.datass.f.psd10 <- list(Y = as.vector(c(pt_polls210$PSD, rep(NA, 12))), N = length(as.vector(pt_polls210$PSD)) + 12, Y1 = as.vector(pt_polls210$PSD)[1], mu0 = 1.5, mu1 = 6)
jags.datass.f.ps10 <- list(Y = as.vector(c(pt_polls210$PS, rep(NA, 12))), N = length(as.vector(pt_polls210$PS)) + 12, Y1 = as.vector(pt_polls210$PS)[1], mu0 = 1.5, mu1 = 6)
jags.datass.f.chega10 <- list(Y = as.vector(c(pt_polls210$CHEGA, rep(NA, 12))), N = length(as.vector(pt_polls210$CHEGA)) + 12, Y1 = as.vector(pt_polls210$CHEGA)[1], mu0 = 1.5, mu1 = 6)
jags.datass.f.others10 <- list(Y = as.vector(c(pt_polls210$Others, rep(NA, 12))), N = length(as.vector(pt_polls210$Others)) + 12, Y1 = as.vector(pt_polls210$Others)[1], mu0 = 1.5, mu1 = 6)


jags.paramsss <- c("EY")

modss.f.psd10 = jags.model(textConnection(jagsscriptss), data=jags.datass.f.psd, n.chains=3)
update(modss.f.psd10, 1e3)
mod_simss.f.psd10 = coda.samples(model=modss.f.psd, variable.names=jags.paramsss, n.iter=5e3)

modss.f.ps10 = jags.model(textConnection(jagsscriptss), data=jags.datass.f.ps, n.chains=3)
update(modss.f.ps10, 1e3)
mod_simss.f.ps10 = coda.samples(model=modss.f.ps, variable.names=jags.paramsss, n.iter=5e3)

modss.f.chega10 = jags.model(textConnection(jagsscriptss), data=jags.datass.f.chega, n.chains=3)
update(modss.f.chega10, 1e3)
mod_simss.f.chega10 = coda.samples(model=modss.f.chega, variable.names=jags.paramsss, n.iter=5e3)

modss.f.others10 = jags.model(textConnection(jagsscriptss), data=jags.datass.f.others, n.chains=3)
update(modss.f.others10, 1e3)
mod_simss.f.others10 = coda.samples(model=modss.f.others, variable.names=jags.paramsss, n.iter=5e3)



sumpsd10 <- summary(mod_simss.f.psd10)
sumps10 <- summary(mod_simss.f.ps10)
sumchega10 <- summary(mod_simss.f.chega10)
sumother10 <- summary(mod_simss.f.others10)


```




## Posterior Analysis


```{r}

library(bayesplot)


p11 <- mcmc_areas(
  mcmcresultspsd ,    
  prob = 0.90,
regex_pars = c("EY")
  ) + 
   labs(title="PSD",
        x ="Value in P.P", y = "Parameter")

p12 <- mcmc_areas(
  mcmcresultsps  ,    
  prob = 0.90,
regex_pars = c("EY")
  ) + 
   labs(title="PS",
        x ="Value in P.P", y = "Parameter")

p13 <- mcmc_areas(
  mcmcresultschega  ,    
  prob = 0.90,
regex_pars = c("EY")
  ) + 
   labs(title="CHEGA",
        x ="Value in P.P", y = "Parameter")


p14 <-mcmc_areas(
  mcmcresultsother,    
  prob = 0.90,
regex_pars = c("EY")
  ) + 
   labs(title="Others",
        x ="Value in P.P", y = "Parameter")

grid.arrange(p11, p12,p13,p14, nrow = 2)

```





## Sensitivity Analysis




```{r message = FALSE}

jagsscriptss <- "
model {  
   # priors on parameters
   u ~ dnorm(0, 1); 
   inv.q ~ dgamma(1, 3); 
   q <- 1/inv.q;
   inv.r ~ dgamma(1.5, 15);
   r <- 1/inv.r; 
   X0 ~ dnorm(Y1, 0.1);
   
   X[1] ~ dnorm(X0 + u, inv.q);
   EY[1] <- X[1];
   Y[1] ~ dnorm(EY[1], inv.r);
   for(i in 2:N) {
      X[i] ~ dnorm(X[i-1] + u, inv.q);
      EY[i] <- X[i];
      Y[i] ~ dnorm(EY[i], inv.r); 
   }
}  
"
jags.paramsss <- c("q", "r", "EY", "u")

jags.datass.psd <- list(Y = as.vector(pt_polls2$PSD), N = length(as.vector(pt_polls2$PSD)), Y1 = as.vector(pt_polls2$PSD)[1])
jags.datass.ps <- list(Y = as.vector(pt_polls2$PS), N = length(as.vector(pt_polls2$PS)), Y1 = as.vector(pt_polls2$PS)[1])
jags.datass.chega <- list(Y = as.vector(pt_polls2$CHEGA), N = length(as.vector(pt_polls2$CHEGA)), Y1 = as.vector(pt_polls2$CHEGA)[1])
jags.datass.others <- list(Y = as.vector(pt_polls2$Others), N = length(as.vector(pt_polls2$Others)), Y1 = as.vector(pt_polls2$Others)[1])


modss.psd = jags.model(textConnection(jagsscriptss), data=jags.datass.psd, n.chains=3)
update(modss.psd, 1e3)
mod_simss.psd = coda.samples(model=modss.psd, variable.names=jags.paramsss, n.iter=5e3)

modss.ps = jags.model(textConnection(jagsscriptss), data=jags.datass.ps, n.chains=3)
update(modss.ps, 1e3)
mod_simss.ps = coda.samples(model=modss.ps, variable.names=jags.paramsss, n.iter=5e3)

modss.chega = jags.model(textConnection(jagsscriptss), data=jags.datass.chega, n.chains=3)
update(modss.chega, 1e3)
mod_simss.chega = coda.samples(model=modss.chega, variable.names=jags.paramsss, n.iter=5e3)

modss.other = jags.model(textConnection(jagsscriptss), data=jags.datass.others, n.chains=3)
update(modss.other, 1e3)
mod_simss.other = coda.samples(model=modss.other, variable.names=jags.paramsss, n.iter=5e3)


mcmcresultspsd = as.mcmc(do.call(rbind, mod_simss.psd))
mcmcresultsps = as.mcmc(do.call(rbind, mod_simss.ps))
mcmcresultschega = as.mcmc(do.call(rbind, mod_simss.chega))
mcmcresultsother = as.mcmc(do.call(rbind, mod_simss.other))

(colMeans(round(mcmcresultspsd,2)))
(colMeans(round(mcmcresultsps,2)))
(colMeans(round(mcmcresultschega,2)))
(colMeans(round(mcmcresultsother,2)))

```

```{r message = FALSE}

jagsscriptss <- "
model {  
   # priors on parameters
   u ~ dnorm(0, 1); 
   inv.q ~ dgamma(1, 3); 
   q <- 1/inv.q;
   inv.r ~ dgamma(1.5, 30);
   r <- 1/inv.r; 
   X0 ~ dnorm(Y1, 0.1);
   
   X[1] ~ dnorm(X0 + u, inv.q);
   EY[1] <- X[1];
   Y[1] ~ dnorm(EY[1], inv.r);
   for(i in 2:N) {
      X[i] ~ dnorm(X[i-1] + u, inv.q);
      EY[i] <- X[i];
      Y[i] ~ dnorm(EY[i], inv.r); 
   }
}  
"
jags.paramsss <- c("q", "r", "EY", "u")

jags.datass.psd <- list(Y = as.vector(pt_polls2$PSD), N = length(as.vector(pt_polls2$PSD)), Y1 = as.vector(pt_polls2$PSD)[1])
jags.datass.ps <- list(Y = as.vector(pt_polls2$PS), N = length(as.vector(pt_polls2$PS)), Y1 = as.vector(pt_polls2$PS)[1])
jags.datass.chega <- list(Y = as.vector(pt_polls2$CHEGA), N = length(as.vector(pt_polls2$CHEGA)), Y1 = as.vector(pt_polls2$CHEGA)[1])
jags.datass.others <- list(Y = as.vector(pt_polls2$Others), N = length(as.vector(pt_polls2$Others)), Y1 = as.vector(pt_polls2$Others)[1])


modss.psd = jags.model(textConnection(jagsscriptss), data=jags.datass.psd, n.chains=3)
update(modss.psd, 1e3)
mod_simss.psd = coda.samples(model=modss.psd, variable.names=jags.paramsss, n.iter=5e3)

modss.ps = jags.model(textConnection(jagsscriptss), data=jags.datass.ps, n.chains=3)
update(modss.ps, 1e3)
mod_simss.ps = coda.samples(model=modss.ps, variable.names=jags.paramsss, n.iter=5e3)

modss.chega = jags.model(textConnection(jagsscriptss), data=jags.datass.chega, n.chains=3)
update(modss.chega, 1e3)
mod_simss.chega = coda.samples(model=modss.chega, variable.names=jags.paramsss, n.iter=5e3)

modss.other = jags.model(textConnection(jagsscriptss), data=jags.datass.others, n.chains=3)
update(modss.other, 1e3)
mod_simss.other = coda.samples(model=modss.other, variable.names=jags.paramsss, n.iter=5e3)


mcmcresultspsd = as.mcmc(do.call(rbind, mod_simss.psd))
mcmcresultsps = as.mcmc(do.call(rbind, mod_simss.ps))
mcmcresultschega = as.mcmc(do.call(rbind, mod_simss.chega))
mcmcresultsother = as.mcmc(do.call(rbind, mod_simss.other))

(colMeans(round(mcmcresultspsd,2)))
(colMeans(round(mcmcresultsps,2)))
(colMeans(round(mcmcresultschega,2)))
(colMeans(round(mcmcresultsother,2)))

```





## Forecasting


```{r message = FALSE}


```
